Add Higher Level Goals to Scope section
w3c/wot-charter-drafts pull request #52
Opened 2023-02-20 19:30 UTC by mmccool

- remove second half of background paragraph which was really about scope
- add short (4-point) list of higher-level goals to start of scope section
- add link to details document after work items (link will only work once #51 is merged)

2023-02-20 23:35 UTC, egekorkan requested changes

2023-02-20 23:35 UTC, egekorkan commented on wot-wg-2023-draft.html
> +      <li>Update the Architecture, Thing Description, Profile, and Discovery specifications
binding templates is missing here but it is not an update. 

Also, I still think (as also pointed out in TAG review of Arch spec) that Arch spec should become informative.

2023-02-21 13:11 UTC, benfrancis commented
> * add link to details document after work items

Does this imply that the Working Group agrees with all of the content of this document? I don't think it has been thoroughly reviewed.

2023-02-21 13:45 UTC, benfrancis commented on wot-wg-2023-draft.html
> +      to HTTP.</li>
This reads as though protocol/payload binding (templates) are currently specific to HTTP

2023-02-21 13:45 UTC, benfrancis commented on wot-wg-2023-draft.html
> +      to address major issues discovered during implementation of the 1.0 and 1.1 specifications.
and add features, not just address issues

2023-02-21 13:45 UTC, benfrancis commented on wot-wg-2023-draft.html
> +      <li>Update and improve security and privacy controls.</li>
Which work items correspond to this summary item?

2023-02-21 13:51 UTC, merged